//==================================================================================
//==================================================================================
// File: HardwareAndCoFlasher.cpp
// Description: Centralized initialization and management of OSCAR_P01
//              hardware resources and software components
//
// Copyright (c) 2025 Dad Design.
//==================================================================================
//==================================================================================

#include <HardwareAndCo.h>
#include "Sections.h"
#include "FlasherClient.h"

//**********************************************************************************
// External handles (generated by CubeMX)
//**********************************************************************************
extern QSPI_HandleTypeDef hqspi;               // QSPI flash interface handle

//**********************************************************************************
// Global instances
//**********************************************************************************

// Flash memory instance
DadDrivers::cW25Q128 __Flash;

//**********************************************************************************
// HardwareAndCoInitialize
// Initializes all hardware peripherals in the correct order
//**********************************************************************************
void HardwareAndCoFlasherInitialize() {

    // Initialize SDRAM memory
    SDRAM_Initialize();

    // Initialize QSPI flash memory
    if (HAL_OK != __Flash.Init(&hqspi, DOUBLE_MODE, FLASH_ADDRESS)) {
        Error_Handler();
    }

    // Configure Memory Protection Unit
    MPU_Config();

    // Invalidate CPU caches for memory consistency
    SCB_InvalidateDCache();
    SCB_InvalidateICache();

    FlasherClient();
}


//**********************************************************************************
// MainLoop
// Main application loop (runs in background)
//**********************************************************************************
void MainLoopFlasher() {
	while(1){

	}
}


// =============================================================================
// Dummy for compatibility
// =============================================================================

//**********************************************************************************
// OnNoteOn
// Handle note on events from USB MIDI
//**********************************************************************************
ITCM void OnNoteOn(uint8_t channel, uint8_t note, uint8_t velocity) {
}

//**********************************************************************************
// OnNoteOff
// Handle note off events from USB MIDI
//**********************************************************************************
ITCM void OnNoteOff(uint8_t channel, uint8_t note, uint8_t velocity) {
}

//**********************************************************************************
// OnControlChange
// Handle control change events from USB MIDI
//**********************************************************************************
ITCM void OnControlChange(uint8_t channel, uint8_t control, uint8_t value) {
}

//**********************************************************************************
// OnProgramChange
// Handle program change events from USB MIDI
//**********************************************************************************
ITCM void OnProgramChange(uint8_t channel, uint8_t program) {
}

//***End of file**************************************************************
